<?php

$ADMIN_EMAIL = "admin@test.com";
$WEBSITE_EMAIL = "admin@test.com";


$USER_TYPE_SELECT = "Select User Type";
$USER_TYPE_PROJECT_CLIENT = "Project Client";
$USER_TYPE_PROJECT_DEVELOPER = "Project Developer"; 
$USER_TYPE_SITE_OPERATOR = "Site Operator";   
$USER_TYPE_ADMIN = "Admin";

$USER_TYPE_ARRAY = array($USER_TYPE_SELECT,$USER_TYPE_PROJECT_CLIENT,$USER_TYPE_PROJECT_DEVELOPER);

$GENDER_SELECT = "Select Gender";
$GENDER_MALE = "Male";
$GENDER_FEMALE = "Female";

$GENDER_ARRAY = array($GENDER_SELECT,$GENDER_MALE,$GENDER_FEMALE);

$COOKIE_EXPIRE = time()+60*60*24*30 ;

$PROJECT_TYPE_SELECT = "Select Project Type" ;
$PROJECT_TYPE_WEB_DEVELOPMENT = "Web Development" ;
$PROJECT_TYPE_GRAPHIC_DESIGNING = "Graphic Designing" ;
$PROJECT_TYPE_DATA_ENTRY = "Data Entry" ;
$PROJECT_TYPE_COPY_WRITING = "Copy Writing" ;
$PROJECT_TYPE_SEO= "SEO" ;
$PROJECT_TYPE_ARTICLE_WRITING= "Article Writing" ;

$PROJECT_TYPES_ARRAY = array($PROJECT_TYPE_SELECT,$PROJECT_TYPE_WEB_DEVELOPMENT ,$PROJECT_TYPE_GRAPHIC_DESIGNING ,$PROJECT_TYPE_DATA_ENTRY ,$PROJECT_TYPE_COPY_WRITING ,$PROJECT_TYPE_SEO ,$PROJECT_TYPE_ARTICLE_WRITING ); 

$SEARCH_PROJECT_BY_PROJECT_TAGS = "Project Tags" ;
$SEARCH_PROJECT_BY_CLIENT_USERNAME = "Client Username" ;
$SEARCH_PROJECT_BY_CLIENT_EMAIL = "Client Email" ;

$SEARCH_PROJECTS_CATEGORIES = array($SEARCH_PROJECT_BY_PROJECT_TAGS ,$SEARCH_PROJECT_BY_CLIENT_USERNAME ,$SEARCH_PROJECT_BY_CLIENT_EMAIL );
 
$PROFILE_STATUS_ACTIVE = "Active" ;
$PROFILE_STATUS_DISABLED = "Disabled" ;

$PROFILE_STATUS_ARRAY = array($PROFILE_STATUS_ACTIVE,$PROFILE_STATUS_DISABLED );

$DEFAULT_AVATAR_PATH = "images/defaultAvatar.gif" ;

$PROJECT_STATUS_AVAILABLE = "Available" ;
$PROJECT_STATUS_ASSIGNED = "Assigned" ;
$PROJECT_STATUS_CANCELLED = "Cancelled" ;
$PROJECT_STATUS_COMPLETED = "Completed" ;

$PROJECT_STATUS_ARRAY = array($PROJECT_STATUS_AVAILABLE,$PROJECT_STATUS_ASSIGNED,$PROJECT_STATUS_CANCELLED ,$PROJECT_STATUS_COMPLETED);

/*$SEARCH_PROJECT_SEARCH_ALL = "Search All";
$SEARCH_PROJECT_PROJECT_TYPE= "Project Type"; 
$SEARCH_PROJECT_PROJECT_TITLE = "Project Title";
$SEARCH_PROJECT_PROJECT_DESRIPTION = "Project Description";
$SEARCH_PROJECT_PROJECT_TAGS = "Project Tags";

$SEARCH_PROJECTS_CATEGORIES = array($SEARCH_PROJECT_SEARCH_ALL ,$SEARCH_PROJECT_PROJECT_TYPE ,$SEARCH_PROJECT_PROJECT_TITLE ,$SEARCH_PROJECT_PROJECT_DESRIPTION ,$SEARCH_PROJECT_PROJECT_TAGS );*/

$PROJECT_REQUEST_STATUS_ACCEPTED = "Accepted" ;
$PROJECT_REQUEST_STATUS_REJECTED = "Rejected" ;
$PROJECT_REQUEST_STATUS_PENDING = "Pending" ;

$SEARCH_USER_SEARCH_ALL = "Search All";
$SEARCH_USER_USERNAME = "Username";
$SEARCH_USER_EMAIL = "Email";
$SEARCH_USER_USER_TYPE = "Uset Type";
$SEARCH_USER_FIRSTNAME = "First Name";
$SEARCH_USER_LASTNAME = "Last Name";
$SEARCH_USER_CITY = "City";
$SEARCH_USER_COUNTRY = "Country";
$SEARCH_USER_PREFERENCES= "User preferences";

$SEARCH_USERS_CATEGORIES = array($SEARCH_USER_SEARCH_ALL ,$SEARCH_USER_USERNAME ,$SEARCH_USER_EMAIL ,$SEARCH_USER_USER_TYPE ,$SEARCH_USER_FIRSTNAME ,$SEARCH_USER_LASTNAME ,$SEARCH_USER_CITY ,$SEARCH_USER_COUNTRY,$SEARCH_USER_PREFERENCES );

$USER_RATING_ARRAY =  array("Rate the user","1","2","3","4","5");

$SEARCH_ISSUE_BY_TAG = "Issue Tag";
$SEARCH_ISSUE_BY_DEV_USERNAME = "Developer Username";
$SEARCH_ISSUE_CATEGORIES = array($SEARCH_ISSUE_BY_TAG,$SEARCH_ISSUE_BY_DEV_USERNAME);

?>